### ISSUE TITLE
Enhancement: Improved Error Handling for User Input

### ISSUE THREAD

**Issue by bysiber** [new92/IGFollowersIncreaser#30]
**Describe the bug**
-> Currently, if a user enters a non-numeric string as input, a ValueError is raised, leading to unexpected program termination.

**Expected behavior**
-> I suggest implementing a more robust user input mechanism using a try and except block. With this enhancement, the program will repeatedly prompt the user for a valid numeric input until one is provided.

**Location of Issue**
+ The suggested change should be applied in the following location:
-> **IGFollowersIncreaser/InstagramFollowers/V3/mainV3.py**
-> **LINE 69**

**BEFORE**
```python
opt=int(input("[>] Please enter a number (from the above ones): "))
```

**AFTER-FIXED**
```python
no_value_err = False
while not no_value_err:
    try:
        opt = int(input("[>] Please enter a number (from the above ones): "))
        no_value_err = True
    except ValueError:
        print ("[!] Please enter a valid number.")
```

**Comment by new92** [comment]
Hey there ! Thanks for mentioning this issue ! I will change it as soon as possible.

**Comment by new92** [comment]
Done ! [URL](https://github.com/new92/IGFollowersIncreaser/blob/main/InstagramFollowers/V3/mainV3.py)

**Comment by bysiber** [comment]
The 69th line is still not inside the try-except block, so the error cannot be avoided; the entered input will still be directly converted to an int and an error will be raised. Therefore, you may need to remove this line because it is already within the try-except scope

**Comment by new92** [comment]
Hey @bysiber, because I can't fully understand your idea do you want to make the change directly to the repo and I'll check it later ?

**Comment by new92** [comment]
Ok so I made the change, here is the [url](https://github.com/new92/IGFollowersIncreaser/blob/main/InstagramFollowers/V3/mainV3.py)

**Comment by new92** [comment]
Ok so I made the change, here is the [url](https://github.com/new92/IGFollowersIncreaser/blob/main/InstagramFollowers/V3/mainV3.py)
